# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


gem "rspec", "~> 3.6"
gem "capybara", "~> 2.15"
gem "chromedriver-helper", "~> 1.1"
gem "selenium-webdriver", "~> 3.6"
gem "httparty", "~> 0.15.6"
gem "byebug", "~> 9.1"
gem "sinatra", "~> 2.0"
gem "sinatra-cors", "~> 1.1"
